baseURL: "https://isaacpierreracine.github.io"
theme: "hugo-theme-stack"
defaultContentLanguage: "fr"
defaultContentLanguageInSubdir: true

params:
  mainSections:
    - art
    - references
  sidebar:
    subtitle: "Art · Design · Films"
  colorScheme:
    toggle: true
    default: auto
  widgets:
    homepage: []
  article:
    toc: true
    readingTime: false
  comments:
    enabled: false
    provider: giscus
    giscus:
      repo: isaacpierreracine/isaacpierreracine.github.io
      repoID: R_kgDOSHGN5A
      category: Announcements
      categoryID: DIC_kwDOSHGN5M4C7Oit
      mapping: pathname
      strict: 0
      reactionsEnabled: 1
      emitMetadata: 0
      inputPosition: bottom
      lightTheme: light
      darkTheme: dark_dimmed
      lang: fr
      loading: lazy
  hero:
    image: hero.jpg
    alt: "Isaac Pierre Racine"

outputs:
  home:
    - html
    - rss
    - json
  section:
    - html
    - rss
  page:
    - html
    - json

languages:
  fr:
    languageName: "Français"
    languageCode: "fr"
    title: "Isaac Pierre Racine"
    weight: 1
    contentDir: "content/fr"
    params:
      sidebar:
        subtitle: "Art · Design · Films"
    menu:
      main:
        - name: Accueil
          url: /fr/
          weight: 1
        - name: Art
          url: /fr/art/
          weight: 2
        - name: Archive
          url: /fr/archives/
          weight: 3
        - name: Liens utiles
          url: /fr/references/
          weight: 4
        - name: À propos
          url: /fr/about/
          weight: 5

  en:
    languageName: "English"
    languageCode: "en"
    title: "Isaac Pierre Racine"
    weight: 2
    contentDir: "content/en"
    params:
      sidebar:
        subtitle: "Art · Design · Films"
    menu:
      main:
        - name: Home
          url: /en/
          weight: 1
        - name: Art
          url: /en/art/
          weight: 2
        - name: Archive
          url: /en/archives/
          weight: 3
        - name: Useful links
          url: /en/references/
          weight: 4
        - name: About
          url: /en/about/
          weight: 5

  es:
    languageName: "Español"
    languageCode: "es"
    title: "Isaac Pierre Racine"
    weight: 3
    contentDir: "content/es"
    params:
      sidebar:
        subtitle: "Art · Design · Films"
    menu:
      main:
        - name: Inicio
          url: /es/
          weight: 1
        - name: Arte
          url: /es/art/
          weight: 2
        - name: Archivo
          url: /es/archives/
          weight: 3
        - name: Enlaces utiles
          url: /es/references/
          weight: 4
        - name: Acerca de
          url: /es/about/
          weight: 5
